- name: Copy sshd configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - { src: 'sshd_config.j2', dest: '/etc/ssh/sshd_config' }
    - { src: '50-redhat.conf.j2', dest: '/etc/ssh/sshd_config.d/50-redhat.conf' }
  notify: Restart sshd
  tags:
    - sshd

- name: Allow sshd to listen on custom port
  redhat.rhel_system_roles.seport:
    ports: "{{ sshd_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  when:
    - sshd_port is defined
  tags:
    - sshd
    - sshd_custom_port
