---
- name: Ensure EPEL repository is enabled
  ansible.builtin.include_tasks: epel_repo.yml
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '10'
  tags:
    - rhel10
    - repositories
    - epel

- name: Ensure CRB repository is enabled
  ansible.builtin.include_tasks: crb_repo.yml
  when:
    - repositories_enable_crb is true
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '10'
  tags:
    - rhel10
    - repositories
    - crb

- name: Ensure extra repositories are enabled
  ansible.builtin.include_tasks: extra_repos.yml
  when:
    - repositories_enable_extra is true
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '10'
  tags:
    - rhel10
    - repositories
    - rpmfusion
