- name: Get the username of the user running this Ansible playbook
  become: false
  ansible.builtin.command: /usr/bin/whoami
  register: user_running_playbook
  changed_when: false
  tags:
    - bash
    - sshd
    - common

- name: Get timezone 
  ansible.builtin.command: /usr/bin/timedatectl
  register: timezone
  changed_when: false
  tags:
    - timezone
    - common

- name: Set timezone to Europe/Helsinki
  ansible.builtin.command: /usr/bin/timedatectl set-timezone Europe/Helsinki
  when: "'Europe/Helsinki' not in timezone.stdout"
  tags:
    - timezone
    - common

- name: Set LANG to en_GB.UTF-8
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    search_string: 'LANG='
    line: 'LANG=en_GB.UTF-8'
  tags:
    - lang
    - common

- name: Set banner
  ansible.builtin.copy:
    src: issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  tags:
    - banner
    - common

- name: Disable core dumps
  ansible.builtin.lineinfile:
    dest: /etc/security/limits.conf
    regexp: '^[#]*\*.*core.*0'
    line: '*               hard    core            0'
  tags:
    - core_dump
    - common

- name: Copy /etc/systemd/coredump.conf
  ansible.builtin.copy:
    src: coredump.conf
    dest: /etc/systemd/coredump.conf
    owner: root
    group: root
    mode: 0640
  tags:
    - core_dump
    - common

- name: Disable core suid core dumps
  ansible.builtin.lineinfile:
    dest: /lib/sysctl.d/50-coredump.conf
    regexp: '^fs.suid_dumpable=2'
    line: '#fs.suid_dumpable=2'
  tags:
    - core_dump
    - sysctl
    - common

- name: Copy sysctl hardening.conf
  ansible.builtin.copy:
    src: 98-hardening.conf
    dest: /etc/sysctl.d/98-hardening.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload sysctl
  tags:
    - sysctl
    - common

- name: Copy journald.conf
  ansible.builtin.copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0640
  tags:
    - journald
    - common

- name: Ensure the Default umask is Defined  Correctly
  ansible.builtin.replace:
    path: '{{ item }}'
    regexp: 'umask 022'
    replace: 'umask 027'
  loop:
    - /etc/bashrc
    - /etc/profile
    - /etc/csh.cshrc
  tags:
    - umask
    - common

- name: Ensure the Default umask is Appended Correctly
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: true
    line: 'umask 027'
  loop:
    - /etc/profile
  tags:
    - umask

- name: Replace user UMASK in /etc/login.defs
  ansible.builtin.replace:
    path: /etc/login.defs
    regexp: '^(\s*)UMASK(\s+).*'
    replace: '\g<1>UMASK\g<2>027'
  tags:
    - umask
    - common

- name: Copy /etc/sudoers
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
  tags:
    - sudo
    - common

