---
- name: Ensure /dev/shm has nodev,nosuid,noexec mount options
  ansible.posix.mount:
    src: tmpfs
    path: /dev/shm
    opts: defaults,nodev,nosuid,noexec
    fstype: tmpfs
    state: mounted
    boot: true
    backup: true
  tags:
    - mounts

- name: Ensure options nodev,nosuid,noexec,x-systemd.device-timeout=0 are set
  ansible.posix.mount:
    src: "UUID={{ item['uuid'] }}"
    path: "{{ item['mount'] }}"
    opts: defaults,nodev,nosuid,noexec,x-systemd.device-timeout=0
    fstype: "{{ item['fstype'] }}"
    state: mounted
    boot: true
  loop: "{{ ansible_facts['mounts'] }}"
  loop_control:
    label: "{{ item['mount'] }}"
  notify: Systemctl daemon-reload
  when:
    - "item['mount'] == '/home' or
      item['mount'] == '/tmp' or
      item['mount'] == '/var/log' or
      item['mount'] == '/var/log/audit' or
      item['mount'] == '/var/tmp'"
  tags:
    - mounts

- name: Ensure options defaults,nodev,nosuid,x-systemd.device-timeout=0 are set
  ansible.posix.mount:
    src: "UUID={{ item['uuid'] }}"
    path: "{{ item['mount'] }}"
    opts: defaults,nodev,nosuid,x-systemd.device-timeout=0
    fstype: "{{ item['fstype'] }}"
    state: mounted
    boot: true
  loop: "{{ ansible_facts['mounts'] }}"
  loop_control:
    label: "{{ item['mount'] }}"
  notify: Systemctl daemon-reload
  when:
    - "item['mount'] == '/var'"
  tags:
    - mounts

- name: Ensure options nodev,nosuid set
  ansible.posix.mount:
    src: "UUID={{ item['uuid'] }}"
    path: "{{ item['mount'] }}"
    opts: defaults,nodev,nosuid
    fstype: "{{ item['fstype'] }}"
    state: mounted
    boot: true
  loop: "{{ ansible_facts['mounts'] }}"
  loop_control:
    label: "{{ item['mount'] }}"
  notify: Systemctl daemon-reload
  when:
    - "item['mount'] == '/boot'"
  tags:
    - mounts
