---
- name: Ensure Ansible requirements as rpms are installed
  hosts: all
  become: true
  vars:
    repositories_enable_crb: false
    repositories_enable_extra: false
  roles:
    - repositories
  tasks:
    - name: Ensure Ansible rpms are installed
      ansible.builtin.dnf:
        name:
          - rhel-system-roles
          - ansible-collection-community-general
          - ansible-collection-ansible-posix
        state: present
