- name: Aide init
  ansible.builtin.command:
    cmd: /usr/sbin/aide --init
    creates: /var/lib/aide/aide.db.gz
  register: aide_init
  tags:
    - aide

- name: Move aide database in place
  ansible.builtin.command:
    cmd: /bin/mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
    creates: /var/lib/aide/aide.db.gz
  tags:
    - aide

- name: Create /root/bin directory
  ansible.builtin.file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: '0750'
  tags:
    - aide

- name: Copy update-aide.sh
  ansible.builtin.copy:
    src: update-aide.sh
    dest: /root/bin/update-aide.sh
    owner: root
    group: root
    mode: '0500'
  tags:
    - aide
