---
- name: Stop and disable services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - avahi-daemon.service
    - avahi-daemon.socket
    - rpcbind.service
    - rpcbind.socket
    - sssd-kcm.service
    - sssd-kcm.socket
  register: services_stop_service
  failed_when:
    - services_stop_service.failed == true
    - '"Could not find the requested service" not in services_stop_service.msg'
  tags:
    - services_disabled
    - services

- name: Stop, disable and mask services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    state: stopped
    masked: true
  loop:
    - avahi-daemon.service
    - avahi-daemon.socket
    - bluetooth.service
    - fwupd-refresh.service
    - fwupd-refresh.timer
    - fwupd.service
    - gssproxy.service
    - packagekit.service
    - packagekit-offline-update.service
    - nfs-server.service
    - nftables.service
    - rpcbind.service
    - rpcbind.socket
  register: services_disable_service
  failed_when:
    - services_disable_service.failed == true
    - '"Could not find the requested service" not in services_disable_service.msg'
  tags:
    - services_masked
    - services

- name: Ensure /etc/chrony.conf has local servers
  ansible.builtin.replace:
    path: /etc/chrony.conf
    regexp: '^pool 2.rhel.pool.ntp.org iburst$'
    replace: |
      server time.mikes.fi iburst
      server time2.mikes.fi iburst
      server time3.mikes.fi iburst
  notify: Restart chronyd.service
  tags:
    - services_chrony
    - services

- name: Enable and start services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - chronyd.service
  tags:
    - services_enabled
    - services

- name: Stop and disable sshd service
  ansible.builtin.systemd_service:
    name: sshd.service
    enabled: false
    state: stopped
  when:
    - sshd_enabled is false
  tags:
    - sshd
    - services_disabled
    - services

- name: Enable and start sshd service
  ansible.builtin.systemd_service:
    name: sshd.service
    enabled: true
    state: started
  when:
    - sshd_enabled is true
  tags:
    - sshd
    - services_enabled
    - services
